# version: '3.8'

services:
  # 1. Database Service----
  db:
    image: mysql:8.0
    container_name: library-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: librarydb
     # MYSQL_USER: root
    volumes:
      - db_data:/var/lib/mysql
      - ./server/src/db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./server/src/db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    networks:
      - app-network

  # No ports section for database, to prevent it from being exposed to the outside world.
  # It can be accessed internally only by the backend on port 3306.

  # Checks continously if MySQL DB is actively accepting connections, before starting up the backend container
  # This prevents backend from crashing.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend API Service----
  backend:
    build: ./server
    container_name: library-backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: librarydb
      DB_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # 3. Frontend Web Service----
  frontend:
    build: ./client
    container_name: library-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

# Isolation: Services talk internally via custom virtual network of bridge type
# Containers can talk to each other by service name
networks:
  app-network:
    driver: bridge

# Data Persistence: MySQL data survives container deletion
# Created a named volume attached to MySQL db path /var/lib/mysql
volumes:
  db_data:
